FROM openjdk:8
COPY target/homework-0.0.1-SNAPSHOT-jar-with-dependencies.jar homework-0.0.1-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "homework-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]