apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
  labels:
    app: homework
spec:
  replicas : 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      name: homework
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: localhost:5000/my-image
        imagePullPolicy: Never
        
